apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-wordpress-service
spec:
  type: {{ .Values.wordpress.service.type }}
  ports:
    - port: {{ .Values.wordpress.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app: wordpress